# Generated by Django 4.2.1 on 2024-01-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('item', models.CharField(choices=[('Song', 'Song'), ('Dance', 'Dance'), ('Skit', 'Skit'), ('Mimicry', 'Mimicry'), ('Mono Act', 'Mono Act'), ('Mono Act', 'Mono Act')], max_length=50)),
            ],
        ),
    ]
