# Generated by Django 4.2.1 on 2024-01-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Individual',
            new_name='People',
        ),
    ]
