# Generated by Django 4.2.1 on 2024-01-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_rename_individual_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='category',
            field=models.CharField(choices=[('Single', 'Single'), ('Group', 'Group')], default='Single', max_length=50),
        ),
        migrations.AddField(
            model_name='people',
            name='father_name',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
