# Generated by Django 4.2.1 on 2024-01-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_people_category_people_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='item',
            field=models.CharField(choices=[('Song', 'Song'), ('Dance', 'Dance'), ('Skit', 'Skit'), ('Mimicry', 'Mimicry'), ('Mono Act', 'Mono Act')], max_length=50),
        ),
    ]
